// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/bo/Desktop/KLOE_BDT/run_bdt/./tree_cut_bdt_tuning.C";

#endif
